# Template for creating per-user agent containers
# This file will be used to generate user-specific docker-compose files

version: '3.8'

services:
  agent-anum:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: autogen-agent  # autogen-agent or claude-code-agent
      args:
        USERNAME: anum
        USER_UID: 1000
        USER_GID: 1000
    container_name: agent-anum
    hostname: anum
    networks:
      - agent-network
    volumes:
      - ./volumes/anum/workspace:/home/anum/workspace
      - ./volumes/anum/claude:/home/anum/.claude
      - ./volumes/anum/config:/home/anum/.config
      - ./volumes/anum/ssh:/home/anum/.ssh:ro
      - ./volumes/anum/gitconfig:/home/anum/.gitconfig:ro
      - ../autogen_agent:/home/anum/autogen_agent:ro
      - ../mcp_servers/discord-mcp:/home/anum/discord-mcp:ro
      - ../vm_cli:/home/anum/vm_cli:ro
    environment:
      - USER=anum
      - AGENT_TYPE=autogen
      - DEVCHAT_HOST_IP=host.docker.internal
      - DISCORD_BOT_TOKEN=${BOT_TOKEN_anum}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  agent-network:
    external: true