# Template for creating per-user agent containers (using quick image)
version: '3.8'

services:
  agent-USERNAME:
    image: webfg-quick:latest
    container_name: agent-USERNAME
    hostname: USERNAME
    networks:
      - agent-network
    volumes:
      - ./volumes/USERNAME/workspace:/home/agent/workspace
      - ./volumes/USERNAME/claude:/home/agent/.claude
      - ./volumes/USERNAME/config:/home/agent/.config
      - ./volumes/USERNAME/ssh:/home/agent/.ssh:ro
      - ./volumes/USERNAME/gitconfig:/home/agent/.gitconfig:ro
      - ../autogen_agent:/home/agent/autogen_agent:ro
      - ../mcp_servers/discord-mcp:/home/agent/discord-mcp:ro
      - ../vm_cli:/home/agent/vm_cli:ro
      - ../docker/docker-entrypoint.sh:/home/agent/entrypoint.sh:ro
    environment:
      - USER=USERNAME
      - AGENT_TYPE=AGENT_TYPE
      - DEVCHAT_HOST_IP=host.docker.internal
      - DISCORD_BOT_TOKEN=${BOT_TOKEN_USERNAME}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEYS}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GITHUB_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    restart: unless-stopped
    entrypoint: ["/home/agent/entrypoint.sh"]

networks:
  agent-network:
    external: true