# Template for creating per-user agent containers
# This file will be used to generate user-specific docker-compose files

version: '3.8'

services:
  agent-homonculus:
    image: webfg:latest
    container_name: agent-homonculus
    hostname: homonculus
    networks:
      - agent-network
    volumes:
      - ./volumes/homonculus/workspace:/home/agent/workspace
      - ./volumes/homonculus/claude:/home/agent/.claude
      - ./volumes/homonculus/config:/home/agent/.config
      - ./volumes/homonculus/ssh:/home/agent/.ssh:ro
      - ./volumes/homonculus/gitconfig:/home/agent/.gitconfig:ro
      - ../autogen_agent:/home/agent/autogen_agent:ro
      - ../mcp_servers/discord-mcp:/home/agent/discord-mcp:ro
      - ../vm_cli:/home/agent/vm_cli:ro
    environment:
      - USER=homonculus
      - AGENT_TYPE=autogen
      - DEVCHAT_HOST_IP=host.docker.internal
      - DISCORD_BOT_TOKEN=${BOT_TOKEN_homonculus}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEYS}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GITHUB_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  agent-network:
    external: true