project_name: coding-agent-knowledge-base
version: "1.0.0"
tags:
  "webfg:owneremail": "admin@webfg.com"
  "webfg:sensitive-data": "False"
  "webfg:severity": "low"
  "webfg:slack-channel": "webfg-coding-agent"