AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation exports for WebFG Coding Agent inference profiles'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, prod, test]
    Description: Environment for deployment
    
  MainProfileArn:
    Type: String
    Description: ARN of the main inference profile
  
  EmbeddingProfileArn:
    Type: String
    Description: ARN of the embedding inference profile

Resources:
  # Dummy resource to satisfy CloudFormation requirement for at least one resource
  DummyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/coding-agent/${Environment}/exports-created"
      Type: String
      Value: !Sub "CloudFormation exports created successfully"
      Description: "Marker to show that CloudFormation exports were created"
      Tags:
        Environment: !Ref Environment
        Project: WebFG-Coding-Agent

Outputs:
  MainProfileArn:
    Description: ARN of the main inference profile
    Value: !Ref MainProfileArn
    Export:
      Name: !Sub "coding-inference-profiles-${Environment}-MainProfileArn"
  
  EmbeddingProfileArn:
    Description: ARN of the embedding inference profile
    Value: !Ref EmbeddingProfileArn
    Export:
      Name: !Sub "coding-inference-profiles-${Environment}-EmbeddingProfileArn"